[package]
name = "justshell"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
gtk = { package = "gtk4", version = "0.8", features = ["v4_12"] }
url = "2.5"
